enum TextureKeys {
  Hero = "hero",
  Hobo = "hobo",
  Rurek = "rurek",
  Szymon = "szymon",
  Pawel = "pawel",
  Bartosz = "bartosz",
  Tiles = "tiles",
  BaseColor = "base-color",
  BaseColorForge = "base-color-forge",
  Buildings = "buildings",
  Props1 = "props-01",
  BackgroundProps = "background-props",
  Tilemap = "tilemap",
  Forge = "forge",
  ForgeProps = "forge-props",
  Magazine = "magazine",
  Home = "home",
  Portal = "portal",
  Grass = "grass",
  GrassProps = "grass-props",
  Background = "background",
  Gryl = "gryl",
}

export default TextureKeys;
